name: flutter_calculator
description: A simple flutter calculator.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ^2.18.6

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: assets/images/icon.png
  android: false
  ios: false
  web:
    generate: true
  windows:
    generate: false
  macos:
    generate: false
